name: Build Sniper
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Build
        run: |
          cat <<EOF > sniper.m
          #import <Foundation/Foundation.h>
          #import <CoreLocation/CoreLocation.h>
          #import <objc/runtime.h>
          @implementation NSObject (Sniper)
          - (struct CLLocationCoordinate2D)fake_coordinate {
              return (struct CLLocationCoordinate2D){24.7136, 46.6753};
          }
          @end
          EOF
          clang -dynamiclib -arch arm64 sniper.m -o libR6X9.dylib -framework Foundation -framework CoreLocation -lobjc -undefined dynamic_lookup
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Final-Dylib
          path: libR6X9.dylib
